### LOGIN ADM
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@atlas.com",
  "senha": "atlas123",
  "lembrar": true
}

### CRIAR USUARIO DE TESTE - ALUNO
POST http://localhost:5000/api/alunos
Content-Type: application/json

{
  "nome": "Aluno Teste",
  "email": "aluno.teste@atlas.com",
  "telefone": "45999990001",
  "data_nascimento": "2008-05-12",
  "cgm": "999000001",
  "senha": "AlunoTeste123"
}

### LOGIN ALUNO DE TESTE
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "aluno.teste@atlas.com",
  "senha": "AlunoTeste123",
  "lembrar": true
}

### LOGIN ADM NOVAMENTE
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@atlas.com",
  "senha": "atlas123",
  "lembrar": true
}

### CRIAR USUARIO DE TESTE - PROFESSOR
POST http://localhost:5000/api/professores
Content-Type: application/json

{
  "nome": "Professor Teste",
  "telefone": "45999990002",
  "atributo": "Professor de Desenvolvimento de Sistemas",
  "login": "professor.teste@atlas.com",
  "senha": "ProfessorTeste123"
}

### LOGIN PROFESSOR DE TESTE
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "professor.teste@atlas.com",
  "senha": "ProfessorTeste123",
  "lembrar": true
}
